AWSTemplateFormatVersion: '2010-09-09'
Description: Creates www+root static site using R53, S3 (root pointed to www), ACM public SSL cert, CloudFront. Waits for SSL cert validation.
Parameters:
  DomainName:
    Type: String
    Description: The DNS name of an Amazon Route 53 hosted zone e.g. ideaowl.com, jevsejev.io... DO NOT add www, it's taken care of.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  DNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join ['', ['Hosted zone for ', !Ref 'DomainName']]
      Name: !Ref 'DomainName'
      HostedZoneTags:
      - Key: Application
        Value: Blog
  PublicSSLCert: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref 'DomainName'
      SubjectAlternativeNames: 
        - !Join ['', ['*.', !Ref 'DomainName']]
      ValidationMethod: DNS
  CloudfrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Name: !Join ['', ['OAC for ', !Ref S3wwwBucket]]
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  S3wwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', ['www.', !Ref 'DomainName']]
      AccessControl: Private
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Retain
  S3wwwBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3wwwBucket'
      PolicyDocument:
        Statement:
        - Sid: AllowCloudFrontServicePrincipalReadOnly
          Effect: Allow
          Principal: 
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3wwwBucket', /*]]
          Condition: 
            StringEquals:
              'AWS:SourceArn': !Join ['', ['arn:aws:cloudfront::', !Ref 'AWS::AccountId', ':distribution/', !Ref 'CloudfrontForS3']]
  CloudfrontForS3:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - S3wwwBucket
    - PublicSSLCert
    Properties:
      DistributionConfig:
        Comment: !Join ['', ['Cloudfront to private S3 for ', !Ref 'DomainName']]
        DefaultRootObject: index.html
        Origins:
        - DomainName: !GetAtt 'S3wwwBucket.DomainName'
          Id: S3Origin
          OriginShield:
            Enabled: true
            OriginShieldRegion: !Ref 'AWS::Region'
          S3OriginConfig:
            OriginAccessIdentity: ''
          OriginAccessControlId: !GetAtt 'CloudfrontOAC.Id'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - !Join ['', ['www.', !Ref 'DomainName']]
        - !Ref 'DomainName'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref PublicSSLCert
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'DomainName', .]]
      RecordSets:
      - Name: !Join ['', ['www.', !Ref 'DomainName']]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt [CloudfrontForS3, DomainName]
      - Name: !Ref 'DomainName'
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt [CloudfrontForS3, DomainName]
Outputs:
  BucketName:
    Value: !Ref 'S3wwwBucket'
    Description: Name of S3 bucket to hold website content
  CloudfrontEndpoint:
    Value: !GetAtt [CloudfrontForS3, DomainName]
    Description: Endpoint for Cloudfront distribution
  FullDomain:
    Value: !Join ['', ['www.', !Ref 'DomainName']]
    Description: Full DomainName
